spring.application.name=bag

spring.datasource.url=${URl_DB}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.key.public=classpath:keys/public_key.pem
jwt.key.private=classpath:keys/private_key.pem

jwt.expiration.time=${EXPIRATION_TIME}