spring.application.name=bag

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${URL_DB}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
spring.liquibase.change-log=classpath:db/master.xml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=none

jwt.key.public=classpath:key/public_key.pem
jwt.key.private=classpath:key/private_key.pem

jwt.expiration.time=${EXPIRATION_TIME}
refresh.expiration.time=${REFRESH_TIME}
spring.admin.email=${ADMIN_EMAIL}
spring.admin.senha=${ADMIN_SENHA}

spring.mail.username=${EMAIL_SENDER}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.port=${EMAIL_PORT}
spring.mail.host=${SMTP_HOST}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.transport.protocol=smtp
mail.debug=true